# External repositories/files that chezmoi can fetch into the destination.
# Refreshed when you run `chezmoi apply`/`chezmoi update` (see `-R/--refresh-externals`).

["node/sub"]
type = "git-repo"
url = "git@github.com:weiying-chen/sub.git"
refreshPeriod = "24h"

["python/watchpick"]
type = "git-repo"
url = "git@github.com:weiying-chen/watchpick.git"
refreshPeriod = "24h"
